#!/bin/bash
# Date : (2017-05-20)
# Last revision : 
# Distribution used to test : Linux Mint
# Author : George Sokianos
# Licence : GPLv3
# WineHQ: 

# Changelog


[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"

WINEVERSION="2.0-staging"

TITLE="Amikit X Setup"
PREFIX="AmikitX"
SHORTCUT_NAME="Amikit X"

POL_GetSetupImages "http://file.amiga.sk/amikit/playonlinux/top.jpg" "http://file.amiga.sk/amikit/playonlinux/left.jpg" "$TITLE_20170520"

POL_SetupWindow_Init
POL_RequiredVersion "4.2.10" || POL_Debug_Fatal "$APPLICATION_TITLE 4.2.10 is required to install $TITLE"

POL_SetupWindow_free_presentation "$TITLE" "Congratulations on purchasing the most complete and\n
up-to-date AmigaOS3.x 68k world in a modern suit!\n
The development of this version took almost 2 years\n
(and an additional 10 years for its predecessor).\n\n
Hope you enjoy it!\n\n
CREDITS\n
AmiKit X by Ján Zahurančík & Contributors\n
AmiKit includes more than 380 of the finest Amiga programs!\n
Graphics by Kenneth E. Lester, Jr.\n
WinUAE by Toni Wilen\n
Windows launcher and RomFind by Rex Schilasky\n
PlayOnLinux install script by George Sokianos
"

POL_SetupWindow_InstallMethod "LOCAL"

if [ "$INSTALL_METHOD" = "LOCAL" ]; then
POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE" "" "Windows Installer (*.msi)|*.msi;*.MSI"
FULL_INSTALLER="$APP_ANSWER"
fi

POL_System_SetArch "x86"
POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WINEVERSION"

POL_Call POL_Install_corefonts
POL_Call POL_Install_d3dx9_43
POL_Call POL_Install_d3dx10
POL_Call POL_Install_d3dx11

"cd $HOME || exit"    # Switch to user's personal directory
# Download latest winetricks and install vcrun2015
wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
chmod +x winetricks
WINEPREFIX="$HOME"/.PlayOnLinux/wineprefix/"$PREFIX" "$HOME"/winetricks -q vcrun2015
rm "$HOME"/winetricks

Set_OS "win7"

POL_Wine_WaitBefore "$TITLE"
GC_DONT_GC=1 POL_AutoWine "$FULL_INSTALLER"
POL_Wine_WaitExit "$TITLE"

#Set_OS winxp

POL_Shortcut "AmiKit.exe" "$SHORTCUT_NAME"
POL_Shortcut "winuae.exe" "$SHORTCUT_NAME WinUAE"

POL_SetupWindow_message "$(eval_gettext 'Complete setup:\n
Now that AmiKit X is installed you will need AmigaOS & ROM files\n
to setup your emulated Amiga system. You can find these at:\n
http://www.amikit.amiga.sk/getamigaos\n\n
You can find a helpful installation guide at:\n
http://bit.ly/AmiKit-QuickGuide\n
AmiKit X features and information can be found at:\n
https://www.amikit.amiga.sk\n\n
AmiKit X is installed at the folder:\n
"$HOME/.PlayOnLinux/wineprefix/$PREFIX/drive_c/Program Files/AmiKit X/"\n\n
Click Next to close this window and revive your memories,\n
enjoy your old computer again, but now in a power suit!.')" "$TITLE"

POL_SetupWindow_Close
exit 0
